### ISSUE TITLE
SetOperModeToDifference not working on a simple case

### ISSUE THREAD

**Issue by truongnn** [zippy84/vtkbool#22] opened 2019-07-09 14:23 UTC
Hello,

I tried SetOperModeToDifference on these two inputs, but it didn't work.
Basically I want to subtract "bottomBox.ply" from "frontAndBackBoxes.ply". My code is like this:

```
// Subtract bottom box
auto subtractOperation = vtkSmartPointer<vtkPolyDataBooleanFilter>::New();
subtractOperation->SetOperModeToDifference();
subtractOperation->SetInputData(0, frontAndBackBoxes);
subtractOperation->SetInputData(1, bottomBox);
subtractOperation->Update();
```

The output has zero cells.
I then tried with CGAL demo app and it worked fine there.
Could you please check this case?

Thanks,
Truong

[Inputs.zip](https://github.com/zippy84/vtkbool/files/3373401/Inputs.zip)

**Comment by zippy84** [comment] 2019-07-09 17:55
There is an error: `ERROR: In /home/zippy/vtkbool/vtkPolyDataBooleanFilter.cxx, line 254
vtkPolyDataBooleanFilter (0x55b74814c020): Contact is ambiguous or incomplete (at point 12).`

This situation is currently not handled. It's not a bug, but thanks for the example.

**Comment by truongnn** [comment] 2019-07-10 00:52
Hi,

Thanks for trying the case.

I'm wondering if you have plans to handle this situation?

Regards,
Truong

**Comment by zippy84** [comment] 2019-07-14 11:33
It's on my todo-list. Stay tuned :smiley:

**Comment by zippy84** [comment] 2019-07-25 19:26
Fixed in master.

**Closed by zippy84** 2019-07-25 19:26 UTC
Labels: bug

**Comment by truongnn** [comment] 2019-07-29 08:05
Hi,

Thanks for making the changes.
However, when I tried your latest code in master, the Boolean Difference result is incorrect. Please see the result "subtractOperation.ply" attached.

Could you try with the inputs attached in my original message?

Thanks,
Truong

[subtractOperation.zip](https://github.com/zippy84/vtkbool/files/3440901/subtractOperation.zip)

**Comment by zippy84** [comment] 2019-07-29 16:42
It works as expected:

```python
import vtkboolPython
import vtk

rA = vtk.vtkPLYReader()
rA.SetFileName('frontAndBackBoxes.ply')

rB = vtk.vtkPLYReader()
rB.SetFileName('bottomBox.ply')

bf = vtkboolPython.vtkPolyDataBooleanFilter();
bf.SetInputConnection(0, rA.GetOutputPort())
bf.SetInputConnection(1, rB.GetOutputPort())
bf.SetOperModeToDifference()

w = vtk.vtkPolyDataWriter()
w.SetInputConnection(bf.GetOutputPort())
w.SetFileName('res.vtk')
w.Update()
```

![res](https://user-images.githubusercontent.com/373343/62066039-8ae5c880-b230-11e9-846a-6cd760a56a8e.png)

**Comment by zippy84** [comment] 2019-07-29 17:56
Your result looks like a Union!

**Comment by truongnn** [comment] 2019-07-30 13:27
Hi,

Thanks for trying.
I found out that when using any of these 4 functions, the "int OperMode;" variable is not changed:
void SetOperModeToUnion () { OperMode = OPER_UNION; };
    void SetOperModeToIntersection () { OperMode = OPER_INTERSECTION; };
    void SetOperModeToDifference () { OperMode = OPER_DIFFERENCE; };
    void SetOperModeToDifference2 () { OperMode = OPER_DIFFERENCE2; };

Instead, I have to use this way for it to work:
SetOperMode(OPER_DIFFERENCE);

I built vtkbool with VS 2013, and link the resulted vtkbool.dll with my project.

BTW, the Difference result contains many boundaries:
![image](https://user-images.githubusercontent.com/1143202/62133109-7543d200-b308-11e9-819b-2f964a5b005c.png)

Regards,
Truong

**Comment by zippy84** [comment] 2019-07-30 13:39
The boundaries are wanted. Use `vtkCleanPolyData` to remove them. I can't say, why the methods not working. It's nothing special.
