### ISSUE TITLE
Undefined symbols for architecture x86_64:   "Point::_tag", referenced in MAC using xcode

### ISSUE THREAD

**Issue by zandarina** [zippy84/vtkbool#35] opened 2020-07-02 09:32 UTC
Hello,

Congratulations for your excellent work. I am trying to compile your library in MAC. I wonder if it is compatible with MAC.
I got the following error:

Undefined symbols for architecture x86_64:
  "Point::_tag", referenced from:
      Point::Point(double, double, int) in vtkPolyDataBooleanFilter.o
      Point::Point(double, double, int) in libmerger.a(Merger.o)
      Point::Point(double, double, int) in libvp.a(VisPoly.o)
      Point::Point(double, double, int) in libvp.a(RmTrivials.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also commented:
//#ifdef _WIN32
//int Point::_tag;
//#endif

but it shouldn't be necessary.

Thank you very much

**Comment by zandarina** [comment] 2020-07-02 09:54
I just did this:

//#ifdef _WIN32
int Point::_tag;
//#endif

And problem solved

**Comment by zippy84** [comment] 2020-11-13 17:24
Duplicate of #15

**Closed by zippy84** 2020-11-13 17:24 UTC
