### ISSUE TITLE
Union does not work for disjoint meshes

### ISSUE THREAD

**Issue by bluelightning32** [zippy84/vtkbool#26] opened 2019-10-21 01:21 UTC
vtkPolyDataBooleanFilter in union mode only works if the two input meshes intersect. Can you change it to also support disjoint meshes? Currently I have to choose vtkPolyDataBooleanFilter or vtkAppendPolyData based on whether they intersect.

**Comment by zippy84** [comment] 2019-10-21 14:34
Duplicate of #19

**Closed by zippy84** 2019-10-21 14:34 UTC
Labels: enhancement
